version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: storyfield-mariadb
    restart: unless-stopped
    ports:
      - "4306:3306"
    env_file:
      - ./.env
    networks:
      - storyfield-app
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: gyeongditor/storyfield-redis:latest
    container_name: storyfield-redis
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "8379:6379"
    networks:
      - storyfield-app
  app:
    image: gyeongditor/story-field-be:latest
    container_name: storyfield-app
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      - storyfield-app
    ports:
      - "9080:8080"
    env_file:
      - ./.env
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
    entrypoint:
      - sh
      - -c
      - |
        set -e
        echo "🔎 checking MariaDB at ${DB_HOST}:${DB_PORT}"
        until nc -z "$$DB_HOST" "$$DB_PORT"; do
          echo "⏳ waiting for MariaDB..."
          sleep 1
        done
        echo "✅ MariaDB OK"
        exec java -jar /app/app.jar

volumes:
  mariadb_data:

networks:
  storyfield-app:
    driver: bridge