name: CD - Deploy on Macmini

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/story-field-be

jobs:
  build-and-deploy:
    runs-on: [self-hosted, macOS]   # 또는 [self-hosted, macmini] (라벨에 맞춰 수정)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR (skip tests)
        run: ./gradlew clean build -x test

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image (multi-arch)
        run: |
          docker buildx create --use --name sf_builder || docker buildx use sf_builder
          docker run --privileged --rm tonistiigi/binfmt:latest --install all || true
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            --push .

      - name: Deploy with Docker Compose
        run: |
          cd /Users/gyeongditor/Documents
          docker compose pull
          docker compose up -d

      - name: Check containers
        run: docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
