# .github/workflows/cd-macmini.yml
name: CD - Deploy on Macmini

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve dynamic paths (no hardcoding)
        run: |
          if [ -n "${{ vars.DEPLOY_DIR }}" ]; then
            echo "DEPLOY_DIR=${{ vars.DEPLOY_DIR }}" >> "$GITHUB_ENV"
          else
            echo "DEPLOY_DIR=$HOME/Documents" >> "$GITHUB_ENV"
          fi

      - name: Quick daemon check
        run: |
          set -e
          docker version
          docker info

      - name: Ensure compose files
        run: |
          set -e
          echo "DEPLOY_DIR=$DEPLOY_DIR"
          ls -al "$DEPLOY_DIR"
          test -f "$DEPLOY_DIR/docker-compose.yml"

      - name: Pull images with compose (no login; uses existing creds)
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose pull
        timeout-minutes: 10

      - name: Deploy with compose
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose up -d

      - name: Check containers
        run: docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
