# .github/workflows/cd-macmini.yml
name: CD - Deploy on Macmini

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, macOS]  # 라벨에 맞춰 조정: [self-hosted], [self-hosted, macOS, ARM64] 등

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve dynamic paths (no hardcoding)
        run: |
          # DEPLOY_DIR: repo variable 있으면 사용, 없으면 $HOME/Documents
          if [ -n "${{ vars.DEPLOY_DIR }}" ]; then
            echo "DEPLOY_DIR=${{ vars.DEPLOY_DIR }}" >> "$GITHUB_ENV"
          else
            echo "DEPLOY_DIR=$HOME/Documents" >> "$GITHUB_ENV"
          fi

          # DOCKER_CONFIG: repo variable 있으면 사용, 없으면 $RUNNER_TEMP/.docker
          if [ -n "${{ vars.DOCKER_CONFIG }}" ]; then
            echo "DOCKER_CONFIG=${{ vars.DOCKER_CONFIG }}" >> "$GITHUB_ENV"
          else
            echo "DOCKER_CONFIG=$RUNNER_TEMP/.docker" >> "$GITHUB_ENV"
          fi

          echo "Using DEPLOY_DIR=$DEPLOY_DIR"
          echo "Using DOCKER_CONFIG=$DOCKER_CONFIG"

      - name: Quick daemon check
        run: |
          set -e
          docker version
          docker info

      - name: Disable macOS Keychain credsStore (per-job)
        run: |
          mkdir -p "$DOCKER_CONFIG"
          echo '{"auths": {}, "credsStore": ""}' > "$DOCKER_CONFIG/config.json"

      - name: Registry reachability sanity check
        run: curl -sS https://registry-1.docker.io/v2/ || true

      - name: Docker login
        uses: docker/login-action@v3
        timeout-minutes: 3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull images with compose
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose pull
        timeout-minutes: 10

      - name: Deploy with compose
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose up -d

      - name: Check containers
        run: docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
