name: CD - Deploy on Macmini

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/story-field-be

jobs:
  deploy:
    runs-on: [self-hosted, macOS]   # runner 라벨 맞추기
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy with Docker Compose
        run: |
          cd /Users/gyeongditor/Documents
          docker compose pull
          docker compose up -d

      - name: Check containers
        run: docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
